section: screens
	mijung-thinkpadp16vgen1.seoul3.csb:
	mijung-p11rha.seoul3.csb:
end
section: links
	mijung-p11rha.seoul3.csb:
		left = mijung-thinkpadp16vgen1.seoul3.csb
	mijung-thinkpadp16vgen1.seoul3.csb:
		right = mijung-p11rha.seoul3.csb
end

section: options
	relativeMouseMoves = true
	screenSaverSync = false
	win32KeepForeground = true
	clipboardSharing = true
	switchCorners = none
	switchCornerSize = 0
	mousebutton(6) = keystroke(WWWBack)
	mousebutton(7) = keystroke(WWWForward)
end
